exports_files(
    [
        "rules/embedded_file_cc_header/TEMPLATE.embed.h",
        "rules/embedded_file_cc_object/TEMPLATE.build_object_file.sh",
    ],
    visibility = ["//visibility:public"],
)
